### ISSUE TITLE
萌新表示不会用啊

### ISSUE THREAD

**Issue by 1812z** [ColorfulGhost/mcbot#1]
怎么用呢，，，

**Comment by Ero-Cat** [comment]
现在在开发阶段.....功能性和代码很烂都没整理....用的话可以加群讨论199324349

**Comment by 1812z** [comment]
> 现在在开发阶段.....功能性和代码很烂都没整理....用的话可以加群讨论199324349

自己编译失败，如果能发布下jar就好了，github-action也行...
